import { useEffect, useRef, useState, type KeyboardEvent, type PointerEvent } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Crosshair, RotateCcw } from 'lucide-react';
import { Button } from './ui/button';
export default function MarkerGame(){
 const [playing,setPlaying]=useState(false);const [score,setScore]=useState(0);const [message,setMessage]=useState('A small field test. Lock onto three markers.');
 const field=useRef<HTMLDivElement>(null);const target=useRef<HTMLSpanElement>(null);const cursor=useRef({x:50,y:50});const position=useRef({x:50,y:50});const reticle=useRef<HTMLSpanElement>(null);
 useEffect(()=>{if(!playing)return;let frame=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const start=performance.now();
 const tick=(now:number)=>{const t=(now-start)/1000;position.current={x:50+Math.sin(t*.7+score*2)*28,y:50+Math.cos(t*.9+score)*24};if(target.current){target.current.style.left=position.current.x+'%';target.current.style.top=position.current.y+'%'}if(!reduced)frame=requestAnimationFrame(tick)};
 frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);
 },[playing,score]);
 function move(x:number,y:number){cursor.current={x:Math.max(2,Math.min(98,x)),y:Math.max(5,Math.min(95,y))};if(reticle.current){reticle.current.style.left=cursor.current.x+'%';reticle.current.style.top=cursor.current.y+'%'}}
 function lock(x=cursor.current.x,y=cursor.current.y){if(!playing)return;const box=field.current?.getBoundingClientRect();if(!box)return;const distance=Math.hypot((x-position.current.x)*box.width/100,(y-position.current.y)*box.height/100);if(distance<27){const next=score+1;setScore(next);setMessage(next===3?'Calibration complete. Three anchors locked.':'Anchor locked. Acquire the next marker.');if(next===3)setPlaying(false)}else setMessage('Almost. Center the reticle on the amber marker.');}
 function pointer(e:PointerEvent<HTMLDivElement>,capture=false){if(!playing)return;const box=e.currentTarget.getBoundingClientRect();const x=(e.clientX-box.left)/box.width*100;const y=(e.clientY-box.top)/box.height*100;move(x,y);if(capture)lock(x,y)}
 function keyboard(e:KeyboardEvent<HTMLDivElement>){const keys=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter',' '];if(!playing||!keys.includes(e.key))return;e.preventDefault();const {x,y}=cursor.current;if(e.key==='Enter'||e.key===' ')lock();else move(x+(e.key==='ArrowRight'?3:e.key==='ArrowLeft'?-3:0),y+(e.key==='ArrowDown'?5:e.key==='ArrowUp'?-5:0));}
 function start(){setScore(0);setMessage('Move to the marker and click to lock.');setPlaying(true);move(50,50);field.current?.focus()}
 return <aside className="calibration"><div className="calibration-copy"><span className="eyebrow">INTERACTIVE / FIELD TEST</span><h3>Can you find the anchor?</h3><p id="game-help">Move your pointer and click the marker. On a keyboard, use arrow keys and Enter. On touch, tap the marker.</p><div className="flex gap-3 flex-wrap"><Button className="button game-button" onClick={playing?()=>{setPlaying(false);setMessage('Session stopped. Start again anytime.')}:start}>{playing?'Stop session':score===3?'Recalibrate':'Start calibration'} <RotateCcw size={15}/></Button><a className="text-link" href="#contact">Skip ↓</a></div></div><div className="game-panel"><div ref={field} className={`game-field ${playing?'playing':''}`} tabIndex={0} role="group" aria-label="Marker alignment field" aria-describedby="game-help" onKeyDown={keyboard} onPointerMove={e=>pointer(e)} onPointerDown={e=>pointer(e,true)}><span className="game-grid-label">AR SESSION / DEMO</span>{playing?<><span ref={target} className="game-target"/><span ref={reticle} className="game-reticle"><Crosshair size={38} strokeWidth={1}/></span></>:<Crosshair className="idle-crosshair" size={60} strokeWidth={.6}/>}<span className="game-score">{score} / 3 LOCKED</span></div><AnimatePresence mode="wait"><motion.p key={message} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.12}} className="game-message" role="status">{message}</motion.p></AnimatePresence></div></aside>
}
